changes updated to uat
egovernments/egov-mdms-data pull request #2835
Opened 2022-10-30 11:39 UTC by prashant-eGov

2022-10-30 11:51 UTC, jagankumar-egov commented
@prashant-eGov  I could not see any changes related to enabling WS module in UAT 
check this file in QA https://github.com/egovernments/egov-mdms-data/blob/c73d0708fcf1a010954cf7c7fb1c0dc16ccc3022/data/pb/tenant/citymodule.json#L360

2022-10-30 12:08 UTC, jagankumar-egov requested changes
@prashant-eGov  check this file some links for PT are missing in UAT mdms 
https://github.com/egovernments/egov-mdms-data/blob/c73d0708fcf1a010954cf7c7fb1c0dc16ccc3022/data/pb/ACCESSCONTROL-ACTIONS-TEST/actions-test.json#L12778

2022-10-30 12:09 UTC, jagankumar-egov commented
@prashant-eGov  check action test of qa and uat , few missing changes please add them as well.

2022-10-31 11:09 UTC, jagankumar-egov approved these changes

2022-11-02 13:15 UTC, sirishrao-egov approved these changes

2022-11-02 13:21 UTC, sathishp-eGov approved these changes

2022-11-02 13:21 UTC, merged